### ISSUE TITLE
希望增加批量下载壁纸的功能，例如时间维度-按月份

### ISSUE THREAD

**Issue by leijunCN** [inwinter04/bing-wallpaper#2]
> 孤舟隐荷出，轻棹染苔归。     ——王褒

#### 最后，期望该issue可以得到冬天大佬的回复，感谢！

**Comment by inwinter04** [comment]
这个提议非常好，今天晚点再给你回复🤗

**Comment by inwinter04** [comment]
功能我写好了，但是是以一个额外的Java程序来实现的。
可能你不清楚，这个项目是从[niumoo/bing-wallpaper](https://github.com/niumoo/bing-wallpaper)克隆来的，所以并不是我做的，因此我才决定用额外的Java程序来实现这个需求。
程序地址：https://github.com/inwinter04/MicroTools/releases/tag/1.0.0
说明文档：https://www.iamdt.cn/archives/1711780461050 (文档写好了晚点发，现在访问会提示404)
希望可以帮助到你！😘

**Comment by leijunCN** [comment]
好的，我了解下项目，十分感谢响应我的需求，祝好！🌺

**Comment by inwinter04** [comment]
❤️如果还有问题可以继续回复本Issue哦😘

**Comment by leijunCN** [comment]
![image](https://github.com/inwinter04/bing-wallpaper/assets/56594594/29a5029e-e8f5-49cb-a358-f391f7f62635)

发现一个问题，传入的图片路径未被成功配置，仍然存储在默认路径下🧐

**Comment by leijunCN** [comment]
![image](https://github.com/inwinter04/bing-wallpaper/assets/56594594/69741657-b549-453e-8aec-a0fc6a2b4307)

新发现一个问题，分辨率获取是否少了一个0，4K应该是3840x2160的分辨率，然而实际获取的图像分辨率为384x216🤣

**Comment by inwinter04** [comment]
> ![image](https://private-user-images.githubusercontent.com/56594594/318391380-69741657-b549-453e-8aec-a0fc6a2b4307.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDE4MzUsIm5iZiI6MTcxMjA0MTUzNSwicGF0aCI6Ii81NjU5NDU5NC8zMTgzOTEzODAtNjk3NDE2NTctYjU0OS00NTNlLThhZWMtYTBmYzZhMmI0MzA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3MDUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODViZDQ5MDljZjA4OTNkNjFhOTc5ODU2Y2EwZjJkZTIzMmRiZDJmZmU1ZmQyZTgyNDE1MTE4OWY3MzBiZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ov_Iv5hMrx41cQ7LM-l-MyOSkZEFDv1XA-6nSZ6II98)
> 
> 新发现一个问题，分辨率获取是否少了一个0，4K应该是3840x2160的分辨率，然而实际获取的图像分辨率为384x216🤣

是我代码写太拉了🤣新版本已修复这两个问题：https://github.com/inwinter04/MicroTools/releases/tag/1.0.0
